version: "2"
services:
  spark-master:
    build:
      context: .
      dockerfile: spark-master.Dockerfile
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==<yourmasternode>"
    volumes:
      - ./files:/app/files
  spark-worker-1:
    build:
      context: .
      dockerfile: spark-worker.Dockerfile
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==<yourworkernode>"
  spark-worker-2:
    build:
      context: .
      dockerfile: spark-worker.Dockerfile
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==<yourworkernode>"
  py-spark:
    build:
      context: .
      dockerfile: pyspark.Dockerfile
    depends_on:
      - spark-master
    environment:
      - ENABLE_INIT_DAEMON=false
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - ./files:/app/files